dist: xenial
language: python
python:
  - 2.7.13
  - 3.4
  - 3.5
  - 3.6
  - 3.7
sudo: false

install:
  - python -m pip install -r requirements_dev.txt

script:
  - python -m unittest discover -p test*
